import prisma from '../config/client.js';

export class ExportService {
  /**
   * Generates a standard OpenAPI 3.1.0 specification
   */
  async generateOpenApiSpec(projectId: string) {
    const project = await prisma.project.findUnique({
      where: { id: projectId },
      include: { endpoints: true }
    });

    if (!project) {
      throw new Error('Project not found');
    }

    const baseUrl = project.repository_url?.startsWith('http') && !project.repository_url.includes('github.com')
      ? project.repository_url.replace(/\/+$/, '')
      : 'https://api.example.com';

    const paths: Record<string, any> = {};

    for (const ep of project.endpoints) {
      const normalizedPath = ep.path.startsWith('/') ? ep.path : `/${ep.path}`;
      if (!paths[normalizedPath]) {
        paths[normalizedPath] = {};
      }

      const methodKey = ep.method.toLowerCase();
      const pathParams = (normalizedPath.match(/\{(\w+)\}|:(\w+)/g) || []).map((p: string) => ({
        name: p.replace(/[{}:]/g, ''),
        in: 'path',
        required: true,
        schema: { type: 'string' },
        description: `Parameter ${p}`
      }));

      const operation: any = {
        summary: `${ep.method} ${normalizedPath}`,
        description: ep.ai_explanation || `Operation for ${ep.method} ${normalizedPath}`,
        parameters: pathParams.length > 0 ? pathParams : undefined,
        responses: {
          '200': {
            description: 'Successful Response',
            content: {
              'application/json': {
                schema: { type: 'object' },
                example: ep.response_schema || { status: 'success' }
              }
            }
          }
        }
      };

      if (['post', 'put', 'patch'].includes(methodKey) && ep.request_schema) {
        operation.requestBody = {
          required: true,
          content: {
            'application/json': {
              schema: { type: 'object' },
              example: ep.request_schema
            }
          }
        };
      }

      paths[normalizedPath][methodKey] = operation;
    }

    return {
      openapi: '3.1.0',
      info: {
        title: `${project.name} API`,
        version: '1.0.0',
        description: `Exported specification for ${project.name} generated by RADIX API Intelligence Platform.`
      },
      servers: [
        {
          url: baseUrl,
          description: 'Target API Server'
        }
      ],
      paths
    };
  }

  /**
   * Generates a Postman Collection v2.1.0
   */
  async generatePostmanCollection(projectId: string) {
    const project = await prisma.project.findUnique({
      where: { id: projectId },
      include: { endpoints: true }
    });

    if (!project) {
      throw new Error('Project not found');
    }

    const baseUrl = project.repository_url?.startsWith('http') && !project.repository_url.includes('github.com')
      ? project.repository_url.replace(/\/+$/, '')
      : 'http://localhost:5000';

    const items = project.endpoints.map(ep => {
      const pathParts = ep.path.split('/').filter(Boolean);
      return {
        name: `${ep.method} ${ep.path}`,
        request: {
          method: ep.method.toUpperCase(),
          header: [
            {
              key: 'Content-Type',
              value: 'application/json',
              type: 'text'
            }
          ],
          url: {
            raw: `{{baseUrl}}${ep.path.startsWith('/') ? ep.path : `/${ep.path}`}`,
            host: ['{{baseUrl}}'],
            path: pathParts
          },
          body: ['POST', 'PUT', 'PATCH'].includes(ep.method.toUpperCase()) && ep.request_schema
            ? {
                mode: 'raw',
                raw: JSON.stringify(ep.request_schema, null, 2),
                options: {
                  raw: { language: 'json' }
                }
              }
            : undefined,
          description: ep.ai_explanation || `Request template for ${ep.method} ${ep.path}`
        },
        response: []
      };
    });

    return {
      info: {
        _postman_id: project.id,
        name: `${project.name} - RADIX Collection`,
        schema: 'https://schema.getpostman.com/json/collection/v2.1.0/collection.json',
        description: `Collection for ${project.name} auto-generated by RADIX Monitoring Platform.`
      },
      item: items,
      variable: [
        {
          key: 'baseUrl',
          value: baseUrl,
          type: 'string'
        }
      ]
    };
  }
}
